// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: Lexico.jflex

package analizadores;

import java_cup.runtime.Symbol;
import java.util.ArrayList;


@SuppressWarnings("fallthrough")
public class Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int MLCOMMENT = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\2\22\0\1\1"+
    "\1\5\1\6\1\7\2\0\1\10\1\0\1\11\1\12"+
    "\1\13\1\0\1\14\1\15\1\16\1\0\12\17\1\20"+
    "\1\21\1\22\1\23\1\24\2\0\32\25\1\26\1\27"+
    "\1\30\1\0\1\25\1\0\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\25\1\40\1\41\1\25\1\42"+
    "\1\25\1\43\1\44\1\45\1\25\1\46\1\47\1\50"+
    "\1\51\2\25\1\52\1\53\1\25\1\54\1\55\1\56"+
    "\7\0\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\3\1\1\4\1\5\1\6"+
    "\1\7\1\1\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\15\16\1\21\1\1\1\22\2\2"+
    "\1\23\1\0\1\24\1\0\1\2\1\25\1\26\1\0"+
    "\1\27\1\30\1\31\2\16\1\32\21\16\1\33\1\34"+
    "\1\35\1\36\11\16\1\37\3\16\1\40\5\16\1\41"+
    "\1\16\1\42\7\16\1\43\1\16\1\44\3\16\1\45"+
    "\1\16\1\46\1\47\2\16\1\50\2\16\1\51\1\16"+
    "\1\52\1\16\1\53\2\16\1\54\1\55\1\56\1\57"+
    "\1\60\1\61\1\16\1\62";

  private static int [] zzUnpackAction() {
    int [] result = new int[134];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\274\0\353\0\u011a\0\u0149"+
    "\0\136\0\136\0\136\0\136\0\u0178\0\u01a7\0\136\0\136"+
    "\0\u01d6\0\u0205\0\u0234\0\u0263\0\136\0\136\0\u0292\0\u02c1"+
    "\0\u02f0\0\u031f\0\u034e\0\u037d\0\u03ac\0\u03db\0\u040a\0\u0439"+
    "\0\u0468\0\u0497\0\u04c6\0\136\0\u04f5\0\136\0\136\0\u0524"+
    "\0\136\0\353\0\136\0\u0553\0\u0582\0\136\0\136\0\u05b1"+
    "\0\136\0\136\0\136\0\u05e0\0\u060f\0\u0263\0\u063e\0\u066d"+
    "\0\u069c\0\u06cb\0\u06fa\0\u0729\0\u0758\0\u0787\0\u07b6\0\u07e5"+
    "\0\u0814\0\u0843\0\u0872\0\u08a1\0\u08d0\0\u08ff\0\u092e\0\136"+
    "\0\136\0\u05b1\0\u0263\0\u095d\0\u098c\0\u09bb\0\u09ea\0\u0a19"+
    "\0\u0a48\0\u0a77\0\u0aa6\0\u0ad5\0\u0263\0\u0b04\0\u0b33\0\u0b62"+
    "\0\u0263\0\u0b91\0\u0bc0\0\u0bef\0\u0c1e\0\u0c4d\0\u0263\0\u0c7c"+
    "\0\u0263\0\u0cab\0\u0cda\0\u0d09\0\u0d38\0\u0d67\0\u0d96\0\u0dc5"+
    "\0\u0263\0\u0df4\0\u0263\0\u0e23\0\u0e52\0\u0e81\0\u0263\0\u0eb0"+
    "\0\u0263\0\u0263\0\u0edf\0\u0f0e\0\u0263\0\u0f3d\0\u0f6c\0\u0263"+
    "\0\u0f9b\0\u0263\0\u0fca\0\u0263\0\u0ff9\0\u1028\0\u0263\0\u0263"+
    "\0\u0263\0\u0263\0\u0263\0\u0263\0\u1057\0\u0263";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[134];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\3\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\3\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\24\1\35"+
    "\2\24\1\36\1\37\1\24\1\40\1\41\1\42\1\43"+
    "\2\24\1\44\1\45\1\46\7\47\1\50\47\47\60\0"+
    "\2\4\1\0\1\4\75\0\1\51\33\0\2\52\1\0"+
    "\3\52\1\53\20\52\1\54\27\52\7\0\1\55\3\0"+
    "\1\56\53\0\1\57\65\0\1\16\55\0\1\60\1\16"+
    "\62\0\1\61\56\0\1\62\56\0\1\63\52\0\1\24"+
    "\5\0\1\24\3\0\23\24\22\0\1\24\5\0\1\24"+
    "\3\0\3\24\1\64\11\24\1\65\1\24\1\66\3\24"+
    "\22\0\1\24\5\0\1\24\3\0\13\24\1\67\7\24"+
    "\22\0\1\24\5\0\1\24\3\0\11\24\1\70\11\24"+
    "\22\0\1\24\5\0\1\24\3\0\1\71\22\24\22\0"+
    "\1\24\5\0\1\24\3\0\21\24\1\72\1\24\22\0"+
    "\1\24\5\0\1\24\3\0\1\73\6\24\1\74\1\24"+
    "\1\75\11\24\22\0\1\24\5\0\1\24\3\0\12\24"+
    "\1\76\10\24\22\0\1\24\5\0\1\24\3\0\20\24"+
    "\1\77\2\24\22\0\1\24\5\0\1\24\3\0\1\24"+
    "\1\100\21\24\22\0\1\24\5\0\1\24\3\0\4\24"+
    "\1\101\16\24\22\0\1\24\5\0\1\24\3\0\4\24"+
    "\1\102\12\24\1\103\3\24\22\0\1\24\5\0\1\24"+
    "\3\0\1\104\14\24\1\105\5\24\22\0\1\24\5\0"+
    "\1\24\3\0\14\24\1\106\1\24\1\107\4\24\60\0"+
    "\1\110\14\0\1\111\43\0\2\52\3\0\52\52\2\55"+
    "\3\0\52\55\17\0\1\112\56\0\1\24\5\0\1\24"+
    "\3\0\3\24\1\113\17\24\22\0\1\24\5\0\1\24"+
    "\3\0\15\24\1\114\5\24\22\0\1\24\5\0\1\24"+
    "\3\0\13\24\1\115\7\24\22\0\1\24\5\0\1\24"+
    "\3\0\4\24\1\116\16\24\22\0\1\24\5\0\1\24"+
    "\3\0\17\24\1\117\3\24\22\0\1\24\5\0\1\24"+
    "\3\0\14\24\1\120\6\24\22\0\1\24\5\0\1\24"+
    "\3\0\11\24\1\121\11\24\22\0\1\24\5\0\1\24"+
    "\3\0\4\24\1\122\4\24\1\123\11\24\22\0\1\24"+
    "\5\0\1\24\3\0\13\24\1\124\7\24\22\0\1\24"+
    "\5\0\1\24\3\0\17\24\1\125\3\24\22\0\1\24"+
    "\5\0\1\24\3\0\11\24\1\126\11\24\22\0\1\24"+
    "\5\0\1\24\3\0\10\24\1\127\12\24\22\0\1\24"+
    "\5\0\1\24\3\0\1\130\22\24\22\0\1\24\5\0"+
    "\1\24\3\0\17\24\1\131\3\24\22\0\1\24\5\0"+
    "\1\24\3\0\13\24\1\132\1\24\1\133\5\24\22\0"+
    "\1\24\5\0\1\24\3\0\1\24\1\134\21\24\22\0"+
    "\1\24\5\0\1\24\3\0\20\24\1\135\2\24\22\0"+
    "\1\24\5\0\1\24\3\0\3\24\1\136\17\24\22\0"+
    "\1\24\5\0\1\24\3\0\4\24\1\137\16\24\22\0"+
    "\1\24\5\0\1\24\3\0\1\140\22\24\22\0\1\24"+
    "\5\0\1\24\3\0\11\24\1\141\11\24\22\0\1\24"+
    "\5\0\1\24\3\0\1\142\22\24\22\0\1\24\5\0"+
    "\1\24\3\0\1\143\22\24\22\0\1\24\5\0\1\24"+
    "\3\0\13\24\1\144\7\24\22\0\1\24\5\0\1\24"+
    "\3\0\16\24\1\145\4\24\22\0\1\24\5\0\1\24"+
    "\3\0\11\24\1\146\11\24\22\0\1\24\5\0\1\24"+
    "\3\0\17\24\1\147\3\24\22\0\1\24\5\0\1\24"+
    "\3\0\1\150\22\24\22\0\1\24\5\0\1\24\3\0"+
    "\11\24\1\151\11\24\22\0\1\24\5\0\1\24\3\0"+
    "\4\24\1\152\16\24\22\0\1\24\5\0\1\24\3\0"+
    "\3\24\1\153\17\24\22\0\1\24\5\0\1\24\3\0"+
    "\15\24\1\154\5\24\22\0\1\24\5\0\1\24\3\0"+
    "\7\24\1\155\13\24\22\0\1\24\5\0\1\24\3\0"+
    "\11\24\1\156\11\24\22\0\1\24\5\0\1\24\3\0"+
    "\4\24\1\157\16\24\22\0\1\24\5\0\1\24\3\0"+
    "\1\160\22\24\22\0\1\24\5\0\1\24\3\0\22\24"+
    "\1\161\22\0\1\24\5\0\1\24\3\0\15\24\1\162"+
    "\5\24\22\0\1\24\5\0\1\24\3\0\1\24\1\163"+
    "\21\24\22\0\1\24\5\0\1\24\3\0\15\24\1\164"+
    "\5\24\22\0\1\24\5\0\1\24\3\0\4\24\1\165"+
    "\16\24\22\0\1\24\5\0\1\24\3\0\3\24\1\166"+
    "\17\24\22\0\1\24\5\0\1\24\3\0\4\24\1\167"+
    "\16\24\22\0\1\24\5\0\1\24\3\0\17\24\1\170"+
    "\3\24\22\0\1\24\5\0\1\24\3\0\2\24\1\171"+
    "\20\24\22\0\1\24\5\0\1\24\3\0\4\24\1\172"+
    "\16\24\22\0\1\24\5\0\1\24\3\0\12\24\1\173"+
    "\10\24\22\0\1\24\5\0\1\24\3\0\4\24\1\174"+
    "\16\24\22\0\1\24\5\0\1\24\3\0\17\24\1\175"+
    "\3\24\22\0\1\24\5\0\1\24\3\0\1\176\22\24"+
    "\22\0\1\24\5\0\1\24\3\0\17\24\1\177\3\24"+
    "\22\0\1\24\5\0\1\24\3\0\16\24\1\200\4\24"+
    "\22\0\1\24\5\0\1\24\3\0\15\24\1\201\5\24"+
    "\22\0\1\24\5\0\1\24\3\0\17\24\1\202\3\24"+
    "\22\0\1\24\5\0\1\24\3\0\6\24\1\203\14\24"+
    "\22\0\1\24\5\0\1\24\3\0\4\24\1\204\16\24"+
    "\22\0\1\24\5\0\1\24\3\0\16\24\1\205\4\24"+
    "\22\0\1\24\5\0\1\24\3\0\4\24\1\206\16\24"+
    "\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[4230];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\5\1\4\11\2\1\2\11\4\1\2\11"+
    "\15\1\1\11\1\1\2\11\1\1\1\11\1\0\1\11"+
    "\1\0\1\1\2\11\1\0\3\11\24\1\2\11\75\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[134];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
  // Lista publica para almacenar los errores lexicos y recuperarnos
  public ArrayList<String[]> listaErroresLexicos = new ArrayList<>();

  private Symbol sym(int type) {
    return new Symbol(type, yyline + 1, yycolumn + 1, yytext());
  }

  private Symbol sym(int type, Object value) {
    return new Symbol(type, yyline + 1, yycolumn + 1, value);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
            switch (zzLexicalState) {
            case YYINITIAL: {
              return new Symbol(sym.EOF, yyline + 1, yycolumn + 1);
            }  // fall though
            case 135: break;
            case MLCOMMENT: {
              yybegin(YYINITIAL);
        return sym(sym.ERROR, "Comentario multilínea sin cerrar al final del archivo");
            }  // fall though
            case 136: break;
            default:
          { return new java_cup.runtime.Symbol(sym.EOF); }
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { // 1. Lo guardamos en la lista
        listaErroresLexicos.add(new String[]{
            "Léxico",
            "El carácter '" + yytext() + "' no pertenece al lenguaje",
            String.valueOf(yyline + 1),
            String.valueOf(yycolumn + 1)
        });

        // 2. RETORNAMOS el token para que la interfaz y el parser se den cuenta
        return sym(sym.ERROR, yytext());
            }
          // fall through
          case 51: break;
          case 2:
            { /* ignore */
            }
          // fall through
          case 52: break;
          case 3:
            { return sym(sym.NOT);
            }
          // fall through
          case 53: break;
          case 4:
            { return sym(sym.PAR_ABRE);
            }
          // fall through
          case 54: break;
          case 5:
            { return sym(sym.PAR_CIERRA);
            }
          // fall through
          case 55: break;
          case 6:
            { return sym(sym.ASTERISCO);
            }
          // fall through
          case 56: break;
          case 7:
            { return sym(sym.COMA);
            }
          // fall through
          case 57: break;
          case 8:
            { return sym(sym.ENTERO, yytext());
            }
          // fall through
          case 58: break;
          case 9:
            { return sym(sym.DOS_PUNTOS);
            }
          // fall through
          case 59: break;
          case 10:
            { return sym(sym.PUNTO_COMA);
            }
          // fall through
          case 60: break;
          case 11:
            { return sym(sym.MENOR);
            }
          // fall through
          case 61: break;
          case 12:
            { return sym(sym.IGUAL);
            }
          // fall through
          case 62: break;
          case 13:
            { return sym(sym.MAYOR);
            }
          // fall through
          case 63: break;
          case 14:
            { return sym(sym.ID, yytext());
            }
          // fall through
          case 64: break;
          case 15:
            { return sym(sym.COR_ABRE);
            }
          // fall through
          case 65: break;
          case 16:
            { return sym(sym.COR_CIERRA);
            }
          // fall through
          case 66: break;
          case 17:
            { return sym(sym.LLAVE_ABRE);
            }
          // fall through
          case 67: break;
          case 18:
            { return sym(sym.LLAVE_CIERRA);
            }
          // fall through
          case 68: break;
          case 19:
            { return sym(sym.DIFERENTE);
            }
          // fall through
          case 69: break;
          case 20:
            { String s = yytext();
                  return sym(sym.CADENA, s.substring(1, s.length()-1));
            }
          // fall through
          case 70: break;
          case 21:
            { // System.out.println("DEBUG: Inicio de comentario multilinea");
        yybegin(MLCOMMENT);
            }
          // fall through
          case 71: break;
          case 22:
            { return sym(sym.AND);
            }
          // fall through
          case 72: break;
          case 23:
            { return sym(sym.MENOR_IGUAL);
            }
          // fall through
          case 73: break;
          case 24:
            { return sym(sym.IGUAL_IGUAL);
            }
          // fall through
          case 74: break;
          case 25:
            { return sym(sym.MAYOR_IGUAL);
            }
          // fall through
          case 75: break;
          case 26:
            { return sym(sym.AT);
            }
          // fall through
          case 76: break;
          case 27:
            { return sym(sym.OR);
            }
          // fall through
          case 77: break;
          case 28:
            { // System.out.println("DEBUG: Fin de comentario multilinea");
        yybegin(YYINITIAL);
            }
          // fall through
          case 78: break;
          case 29:
            { return sym(sym.DECIMAL, yytext());
            }
          // fall through
          case 79: break;
          case 30:
            { return sym(sym.ADD);
            }
          // fall through
          case 80: break;
          case 31:
            { return sym(sym.T_INT);
            }
          // fall through
          case 81: break;
          case 32:
            { return sym(sym.SET);
            }
          // fall through
          case 82: break;
          case 33:
            { return sym(sym.USE);
            }
          // fall through
          case 83: break;
          case 34:
            { return sym(sym.T_BOOL);
            }
          // fall through
          case 84: break;
          case 35:
            { return sym(sym.NULL);
            }
          // fall through
          case 85: break;
          case 36:
            { return sym(sym.READ);
            }
          // fall through
          case 86: break;
          case 37:
            { return sym(sym.TRUE);
            }
          // fall through
          case 87: break;
          case 38:
            { return sym(sym.T_ARRAY);
            }
          // fall through
          case 88: break;
          case 39:
            { return sym(sym.CLEAR);
            }
          // fall through
          case 89: break;
          case 40:
            { return sym(sym.FALSE);
            }
          // fall through
          case 90: break;
          case 41:
            { return sym(sym.T_FLOAT);
            }
          // fall through
          case 91: break;
          case 42:
            { return sym(sym.STORE);
            }
          // fall through
          case 92: break;
          case 43:
            { return sym(sym.TABLE);
            }
          // fall through
          case 93: break;
          case 44:
            { return sym(sym.EXPORT);
            }
          // fall through
          case 94: break;
          case 45:
            { return sym(sym.FIELDS);
            }
          // fall through
          case 95: break;
          case 46:
            { return sym(sym.FILTER);
            }
          // fall through
          case 96: break;
          case 47:
            { return sym(sym.T_OBJECT);
            }
          // fall through
          case 97: break;
          case 48:
            { return sym(sym.T_STRING);
            }
          // fall through
          case 98: break;
          case 49:
            { return sym(sym.UPDATE);
            }
          // fall through
          case 99: break;
          case 50:
            { return sym(sym.DATABASE);
            }
          // fall through
          case 100: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
