
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

import java_cup.runtime.Symbol;
import ejecucion.*;
import java.util.LinkedList;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Sintactico extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Sintactico() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Sintactico(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Sintactico(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\123\000\002\002\004\000\002\002\003\000\002\003" +
    "\004\000\002\003\002\000\002\004\003\000\002\004\003" +
    "\000\002\004\003\000\002\004\003\000\002\004\003\000" +
    "\002\004\003\000\002\004\003\000\002\004\003\000\002" +
    "\004\004\000\002\004\004\000\002\005\007\000\002\005" +
    "\007\000\002\015\006\000\002\015\002\000\002\006\005" +
    "\000\002\006\005\000\002\007\007\000\002\007\007\000" +
    "\002\016\004\000\002\016\003\000\002\017\006\000\002" +
    "\020\003\000\002\020\003\000\002\020\003\000\002\020" +
    "\003\000\002\020\003\000\002\020\003\000\002\010\011" +
    "\000\002\010\010\000\002\010\010\000\002\010\007\000" +
    "\002\010\010\000\002\010\007\000\002\021\006\000\002" +
    "\021\006\000\002\023\005\000\002\023\003\000\002\022" +
    "\006\000\002\011\005\000\002\011\005\000\002\012\010" +
    "\000\002\012\007\000\002\012\010\000\002\012\007\000" +
    "\002\025\005\000\002\025\003\000\002\026\005\000\002" +
    "\013\014\000\002\013\013\000\002\013\013\000\002\013" +
    "\012\000\002\013\010\000\002\013\007\000\002\027\005" +
    "\000\002\027\003\000\002\030\005\000\002\014\005\000" +
    "\002\014\005\000\002\031\003\000\002\031\003\000\002" +
    "\031\003\000\002\031\003\000\002\031\003\000\002\031" +
    "\003\000\002\031\003\000\002\032\005\000\002\032\004" +
    "\000\002\033\005\000\002\033\003\000\002\024\005\000" +
    "\002\024\005\000\002\024\004\000\002\024\005\000\002" +
    "\024\005\000\002\024\005\000\002\024\005\000\002\024" +
    "\005\000\002\024\005\000\002\024\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\236\000\026\002\ufffe\003\ufffe\004\ufffe\005\ufffe\006" +
    "\ufffe\007\ufffe\014\ufffe\015\ufffe\016\ufffe\020\ufffe\001\002" +
    "\000\026\002\000\003\024\004\021\005\025\006\016\007" +
    "\007\014\026\015\022\016\027\020\011\001\002\000\004" +
    "\002\006\001\002\000\004\002\001\001\002\000\004\056" +
    "\215\001\002\000\026\002\ufff7\003\ufff7\004\ufff7\005\ufff7" +
    "\006\ufff7\007\ufff7\014\ufff7\015\ufff7\016\ufff7\020\ufff7\001" +
    "\002\000\006\003\212\056\211\001\002\000\026\002\ufff8" +
    "\003\ufff8\004\ufff8\005\ufff8\006\ufff8\007\ufff8\014\ufff8\015" +
    "\ufff8\016\ufff8\020\ufff8\001\002\000\026\002\ufff9\003\ufff9" +
    "\004\ufff9\005\ufff9\006\ufff9\007\ufff9\014\ufff9\015\ufff9\016" +
    "\ufff9\020\ufff9\001\002\000\026\002\ufffa\003\ufffa\004\ufffa" +
    "\005\ufffa\006\ufffa\007\ufffa\014\ufffa\015\ufffa\016\ufffa\020" +
    "\ufffa\001\002\000\026\002\ufffc\003\ufffc\004\ufffc\005\ufffc" +
    "\006\ufffc\007\ufffc\014\ufffc\015\ufffc\016\ufffc\020\ufffc\001" +
    "\002\000\004\056\167\001\002\000\026\002\ufffd\003\ufffd" +
    "\004\ufffd\005\ufffd\006\ufffd\007\ufffd\014\ufffd\015\ufffd\016" +
    "\ufffd\020\ufffd\001\002\000\026\002\ufffb\003\ufffb\004\ufffb" +
    "\005\ufffb\006\ufffb\007\ufffb\014\ufffb\015\ufffb\016\ufffb\020" +
    "\ufffb\001\002\000\004\056\155\001\002\000\004\056\137" +
    "\001\002\000\026\002\ufff6\003\ufff6\004\ufff6\005\ufff6\006" +
    "\ufff6\007\ufff6\014\ufff6\015\ufff6\016\ufff6\020\ufff6\001\002" +
    "\000\006\033\135\041\136\001\002\000\006\003\132\056" +
    "\131\001\002\000\006\003\125\057\126\001\002\000\004" +
    "\056\031\001\002\000\026\002\uffff\003\uffff\004\uffff\005" +
    "\uffff\006\uffff\007\uffff\014\uffff\015\uffff\016\uffff\020\uffff" +
    "\001\002\000\004\032\032\001\002\000\006\003\033\017" +
    "\034\001\002\000\004\033\123\001\002\000\004\040\035" +
    "\001\002\000\004\056\036\001\002\000\004\055\121\001" +
    "\002\000\006\041\uffc7\042\uffc7\001\002\000\006\041\042" +
    "\042\041\001\002\000\004\056\036\001\002\000\006\011" +
    "\044\033\043\001\002\000\030\002\uffcb\003\uffcb\004\uffcb" +
    "\005\uffcb\006\uffcb\007\uffcb\014\uffcb\015\uffcb\016\uffcb\020" +
    "\uffcb\041\117\001\002\000\004\040\050\001\002\000\004" +
    "\033\046\001\002\000\030\002\uffcc\003\uffcc\004\uffcc\005" +
    "\uffcc\006\uffcc\007\uffcc\014\uffcc\015\uffcc\016\uffcc\020\uffcc" +
    "\041\047\001\002\000\026\002\uffce\003\uffce\004\uffce\005" +
    "\uffce\006\uffce\007\uffce\014\uffce\015\uffce\016\uffce\020\uffce" +
    "\001\002\000\010\034\052\054\053\056\051\001\002\000" +
    "\016\044\072\045\071\046\065\047\066\050\070\051\067" +
    "\001\002\000\010\034\052\054\053\056\051\001\002\000" +
    "\010\034\052\054\053\056\051\001\002\000\010\041\056" +
    "\052\055\053\057\001\002\000\010\034\052\054\053\056" +
    "\051\001\002\000\004\033\uffd8\001\002\000\010\034\052" +
    "\054\053\056\051\001\002\000\012\035\uffb8\041\uffb8\052" +
    "\055\053\uffb8\001\002\000\012\035\uffb7\041\uffb7\052\uffb7" +
    "\053\uffb7\001\002\000\012\035\uffb6\041\uffb6\052\uffb6\053" +
    "\uffb6\001\002\000\010\035\064\052\055\053\057\001\002" +
    "\000\012\035\uffb5\041\uffb5\052\uffb5\053\uffb5\001\002\000" +
    "\020\027\076\030\100\031\077\036\101\057\073\060\075" +
    "\061\074\001\002\000\020\027\076\030\100\031\077\036" +
    "\101\057\073\060\075\061\074\001\002\000\020\027\076" +
    "\030\100\031\077\036\101\057\073\060\075\061\074\001" +
    "\002\000\020\027\076\030\100\031\077\036\101\057\073" +
    "\060\075\061\074\001\002\000\020\027\076\030\100\031" +
    "\077\036\101\057\073\060\075\061\074\001\002\000\020" +
    "\027\076\030\100\031\077\036\101\057\073\060\075\061" +
    "\074\001\002\000\020\033\uffc3\035\uffc3\037\uffc3\041\uffc3" +
    "\042\uffc3\052\uffc3\053\uffc3\001\002\000\020\033\uffc1\035" +
    "\uffc1\037\uffc1\041\uffc1\042\uffc1\052\uffc1\053\uffc1\001\002" +
    "\000\020\033\uffc2\035\uffc2\037\uffc2\041\uffc2\042\uffc2\052" +
    "\uffc2\053\uffc2\001\002\000\020\033\uffc0\035\uffc0\037\uffc0" +
    "\041\uffc0\042\uffc0\052\uffc0\053\uffc0\001\002\000\020\033" +
    "\uffbe\035\uffbe\037\uffbe\041\uffbe\042\uffbe\052\uffbe\053\uffbe" +
    "\001\002\000\020\033\uffbf\035\uffbf\037\uffbf\041\uffbf\042" +
    "\uffbf\052\uffbf\053\uffbf\001\002\000\022\027\076\030\100" +
    "\031\077\036\101\037\104\057\073\060\075\061\074\001" +
    "\002\000\012\035\uffb0\041\uffb0\052\uffb0\053\uffb0\001\002" +
    "\000\020\033\uffbd\035\uffbd\037\uffbd\041\uffbd\042\uffbd\052" +
    "\uffbd\053\uffbd\001\002\000\020\033\uffbb\035\uffbb\037\uffbb" +
    "\041\uffbb\042\uffbb\052\uffbb\053\uffbb\001\002\000\006\037" +
    "\uffb9\042\uffb9\001\002\000\006\037\110\042\107\001\002" +
    "\000\020\027\076\030\100\031\077\036\101\057\073\060" +
    "\075\061\074\001\002\000\020\033\uffbc\035\uffbc\037\uffbc" +
    "\041\uffbc\042\uffbc\052\uffbc\053\uffbc\001\002\000\006\037" +
    "\uffba\042\uffba\001\002\000\012\035\uffaf\041\uffaf\052\uffaf" +
    "\053\uffaf\001\002\000\012\035\uffb2\041\uffb2\052\uffb2\053" +
    "\uffb2\001\002\000\012\035\uffb1\041\uffb1\052\uffb1\053\uffb1" +
    "\001\002\000\012\035\uffb3\041\uffb3\052\uffb3\053\uffb3\001" +
    "\002\000\012\035\uffb4\041\uffb4\052\uffb4\053\uffb4\001\002" +
    "\000\026\002\uffcd\003\uffcd\004\uffcd\005\uffcd\006\uffcd\007" +
    "\uffcd\014\uffcd\015\uffcd\016\uffcd\020\uffcd\001\002\000\006" +
    "\041\uffc8\042\uffc8\001\002\000\020\027\076\030\100\031" +
    "\077\036\101\057\073\060\075\061\074\001\002\000\006" +
    "\041\uffc6\042\uffc6\001\002\000\030\002\uffc9\003\uffc9\004" +
    "\uffc9\005\uffc9\006\uffc9\007\uffc9\014\uffc9\015\uffc9\016\uffc9" +
    "\020\uffc9\041\124\001\002\000\026\002\uffca\003\uffca\004" +
    "\uffca\005\uffca\006\uffca\007\uffca\014\uffca\015\uffca\016\uffca" +
    "\020\uffca\001\002\000\004\041\130\001\002\000\004\041" +
    "\127\001\002\000\026\002\uffd7\003\uffd7\004\uffd7\005\uffd7" +
    "\006\uffd7\007\uffd7\014\uffd7\015\uffd7\016\uffd7\020\uffd7\001" +
    "\002\000\026\002\uffd6\003\uffd6\004\uffd6\005\uffd6\006\uffd6" +
    "\007\uffd6\014\uffd6\015\uffd6\016\uffd6\020\uffd6\001\002\000" +
    "\004\041\134\001\002\000\004\041\133\001\002\000\026" +
    "\002\uffee\003\uffee\004\uffee\005\uffee\006\uffee\007\uffee\014" +
    "\uffee\015\uffee\016\uffee\020\uffee\001\002\000\026\002\uffef" +
    "\003\uffef\004\uffef\005\uffef\006\uffef\007\uffef\014\uffef\015" +
    "\uffef\016\uffef\020\uffef\001\002\000\026\002\ufff4\003\ufff4" +
    "\004\ufff4\005\ufff4\006\ufff4\007\ufff4\014\ufff4\015\ufff4\016" +
    "\ufff4\020\ufff4\001\002\000\026\002\ufff5\003\ufff5\004\ufff5" +
    "\005\ufff5\006\ufff5\007\ufff5\014\ufff5\015\ufff5\016\ufff5\020" +
    "\ufff5\001\002\000\004\032\140\001\002\000\006\003\143" +
    "\056\141\001\002\000\004\040\153\001\002\000\006\033" +
    "\150\042\147\001\002\000\004\033\145\001\002\000\006" +
    "\033\uffd0\042\uffd0\001\002\000\030\002\uffd2\003\uffd2\004" +
    "\uffd2\005\uffd2\006\uffd2\007\uffd2\014\uffd2\015\uffd2\016\uffd2" +
    "\020\uffd2\041\146\001\002\000\026\002\uffd3\003\uffd3\004" +
    "\uffd3\005\uffd3\006\uffd3\007\uffd3\014\uffd3\015\uffd3\016\uffd3" +
    "\020\uffd3\001\002\000\004\056\141\001\002\000\030\002" +
    "\uffd4\003\uffd4\004\uffd4\005\uffd4\006\uffd4\007\uffd4\014\uffd4" +
    "\015\uffd4\016\uffd4\020\uffd4\041\151\001\002\000\026\002" +
    "\uffd5\003\uffd5\004\uffd5\005\uffd5\006\uffd5\007\uffd5\014\uffd5" +
    "\015\uffd5\016\uffd5\020\uffd5\001\002\000\006\033\uffd1\042" +
    "\uffd1\001\002\000\020\027\076\030\100\031\077\036\101" +
    "\057\073\060\075\061\074\001\002\000\006\033\uffcf\042" +
    "\uffcf\001\002\000\004\032\156\001\002\000\010\003\160" +
    "\012\157\033\ufff0\001\002\000\004\013\164\001\002\000" +
    "\004\033\163\001\002\000\004\033\162\001\002\000\026" +
    "\002\ufff3\003\ufff3\004\ufff3\005\ufff3\006\ufff3\007\ufff3\014" +
    "\ufff3\015\ufff3\016\ufff3\020\ufff3\001\002\000\026\002\ufff2" +
    "\003\ufff2\004\ufff2\005\ufff2\006\ufff2\007\ufff2\014\ufff2\015" +
    "\ufff2\016\ufff2\020\ufff2\001\002\000\004\057\165\001\002" +
    "\000\004\041\166\001\002\000\004\033\ufff1\001\002\000" +
    "\004\032\170\001\002\000\006\003\172\056\171\001\002" +
    "\000\004\040\200\001\002\000\004\033\177\001\002\000" +
    "\006\033\uffea\056\uffea\001\002\000\006\033\175\056\171" +
    "\001\002\000\026\002\uffed\003\uffed\004\uffed\005\uffed\006" +
    "\uffed\007\uffed\014\uffed\015\uffed\016\uffed\020\uffed\001\002" +
    "\000\006\033\uffeb\056\uffeb\001\002\000\026\002\uffec\003" +
    "\uffec\004\uffec\005\uffec\006\uffec\007\uffec\014\uffec\015\uffec" +
    "\016\uffec\020\uffec\001\002\000\016\021\206\022\204\023" +
    "\202\024\201\025\203\026\205\001\002\000\004\041\uffe5" +
    "\001\002\000\004\041\uffe6\001\002\000\004\041\uffe4\001" +
    "\002\000\004\041\uffe7\001\002\000\004\041\uffe3\001\002" +
    "\000\004\041\uffe8\001\002\000\004\041\210\001\002\000" +
    "\006\033\uffe9\056\uffe9\001\002\000\004\041\214\001\002" +
    "\000\004\041\213\001\002\000\026\002\uffc4\003\uffc4\004" +
    "\uffc4\005\uffc4\006\uffc4\007\uffc4\014\uffc4\015\uffc4\016\uffc4" +
    "\020\uffc4\001\002\000\026\002\uffc5\003\uffc5\004\uffc5\005" +
    "\uffc5\006\uffc5\007\uffc5\014\uffc5\015\uffc5\016\uffc5\020\uffc5" +
    "\001\002\000\004\032\216\001\002\000\006\003\217\010" +
    "\221\001\002\000\004\033\237\001\002\000\006\011\044" +
    "\033\232\001\002\000\004\040\222\001\002\000\006\043" +
    "\224\056\223\001\002\000\006\041\uffd9\042\uffd9\001\002" +
    "\000\004\041\231\001\002\000\006\041\227\042\226\001" +
    "\002\000\004\056\230\001\002\000\006\011\uffdc\033\uffdc" +
    "\001\002\000\006\041\uffda\042\uffda\001\002\000\006\011" +
    "\uffdb\033\uffdb\001\002\000\030\002\uffdf\003\uffdf\004\uffdf" +
    "\005\uffdf\006\uffdf\007\uffdf\014\uffdf\015\uffdf\016\uffdf\020" +
    "\uffdf\041\236\001\002\000\004\033\234\001\002\000\030" +
    "\002\uffe0\003\uffe0\004\uffe0\005\uffe0\006\uffe0\007\uffe0\014" +
    "\uffe0\015\uffe0\016\uffe0\020\uffe0\041\235\001\002\000\026" +
    "\002\uffe2\003\uffe2\004\uffe2\005\uffe2\006\uffe2\007\uffe2\014" +
    "\uffe2\015\uffe2\016\uffe2\020\uffe2\001\002\000\026\002\uffe1" +
    "\003\uffe1\004\uffe1\005\uffe1\006\uffe1\007\uffe1\014\uffe1\015" +
    "\uffe1\016\uffe1\020\uffe1\001\002\000\030\002\uffdd\003\uffdd" +
    "\004\uffdd\005\uffdd\006\uffdd\007\uffdd\014\uffdd\015\uffdd\016" +
    "\uffdd\020\uffdd\041\240\001\002\000\026\002\uffde\003\uffde" +
    "\004\uffde\005\uffde\006\uffde\007\uffde\014\uffde\015\uffde\016" +
    "\uffde\020\uffde\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\236\000\006\002\004\003\003\001\001\000\024\004" +
    "\027\005\014\006\016\007\017\010\013\011\012\012\011" +
    "\013\007\014\022\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\027\037\030\036\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\030\117\001\001\000\004" +
    "\022\044\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\024\053\001\001\000\002\001\001\000\004\024\062\001" +
    "\001\000\004\024\061\001\001\000\002\001\001\000\004" +
    "\024\060\001\001\000\002\001\001\000\004\024\057\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\031\115\032" +
    "\102\001\001\000\006\031\114\032\102\001\001\000\006" +
    "\031\113\032\102\001\001\000\006\031\112\032\102\001" +
    "\001\000\006\031\111\032\102\001\001\000\006\031\101" +
    "\032\102\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\031\104\032\102\033\105\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\031\110\032\102\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\031\121\032\102\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\025" +
    "\141\026\143\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\026\151\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\031\153\032" +
    "\102\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\015\160\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\016\173\017\172\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\017\175\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\020\206\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\021\217\001\001\000" +
    "\002\001\001\000\004\022\232\001\001\000\002\001\001" +
    "\000\004\023\224\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Sintactico$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Sintactico$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Sintactico$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    // Variables para conectar con la Interfaz Grafica
    private java.util.function.Consumer<String> log = null;
    private java.util.function.Consumer<String[]> errSink = null;

    // BANDERA: Indica si se detectó algún error durante el parseo
    public boolean hayErrores = false;

    // -------------------------------------------------------------------------
    // CONSTRUCTOR PERSONALIZADO (3 Argumentos)
    // -------------------------------------------------------------------------
    public Sintactico(java_cup.runtime.Scanner s,
                      java.util.function.Consumer<String> log,
                      java.util.function.Consumer<String[]> errSink) {
        super(s);
        this.log = log;
        this.errSink = errSink;
    }

    private void emit(String msg) {
        if (log != null) log.accept(msg);
        else System.out.println(msg);
    }

    private void pushErr(String tipo, String desc, Symbol sym) {
        if (errSink != null && sym != null) {
            errSink.accept(new String[]{ tipo, desc, String.valueOf(sym.left), String.valueOf(sym.right) });
        }
    }

    // NUEVO MÉTODO: Inyecta errores a la tabla sin romper el parser
    public void reportar_error_manual(String mensaje, int linea, int columna) {
        this.hayErrores = true;
        emit("Error Sintáctico: " + mensaje + " [Linea: " + linea + ", Columna: " + columna + "]");
        if (errSink != null) {
            errSink.accept(new String[]{ "Sintáctico", mensaje, String.valueOf(linea), String.valueOf(columna) });
        }
    }

    // Se ejecuta cuando CUP detecta un error nativo
    @Override
    public void syntax_error(Symbol s) {
        this.hayErrores = true;
        String lexema = (s.value != null) ? s.value.toString() : "Token desconocido";
        String mensaje = (s.sym == sym.EOF)
            ? "Se alcanzó el final del archivo inesperadamente. Verifica que no falte cerrar una llave '}' o un punto y coma ';'."
            : "Sintaxis incorrecta cerca de '" + lexema + "'.";

        emit("Error Sintáctico: " + mensaje + " [Linea: " + s.left + ", Columna: " + s.right + "]");
        pushErr("Sintáctico", mensaje, s);
    }

    @Override
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception {
        this.hayErrores = true;
        String lexema = (s.value != null) ? s.value.toString() : "elemento";
        String mensaje = "Error Fatal irrecuperable cerca de '" + lexema + "'.";
        emit("Error Fatal: " + mensaje + " [Linea: " + s.left + ", Columna: " + s.right + "]");
        pushErr("Sintáctico", mensaje, s);
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Sintactico$actions {
  private final Sintactico parser;

  /** Constructor */
  CUP$Sintactico$actions(Sintactico parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Sintactico$do_action_part00000000(
    int                        CUP$Sintactico$act_num,
    java_cup.runtime.lr_parser CUP$Sintactico$parser,
    java.util.Stack            CUP$Sintactico$stack,
    int                        CUP$Sintactico$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Sintactico$result;

      /* select the action based on the action number */
      switch (CUP$Sintactico$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		LinkedList<Instruccion> start_val = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		RESULT = start_val;
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Sintactico$parser.done_parsing();
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // program ::= stmts 
            {
              LinkedList<Instruccion> RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		LinkedList<Instruccion> s = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
         //devuelve la lista completa de instrucciones
         RESULT = s;
      
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // stmts ::= stmts stmt 
            {
              LinkedList<Instruccion> RESULT =null;
		int listaleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int listaright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		LinkedList<Instruccion> lista = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Instruccion s = (Instruccion)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
         //agregar la instrucción a la lista
         if (s != null) lista.add(s);
         RESULT = lista;
      
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("stmts",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // stmts ::= 
            {
              LinkedList<Instruccion> RESULT =null;
		
         //crear la lista vacía
         RESULT = new LinkedList<>();
      
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("stmts",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // stmt ::= use_def 
            {
              Instruccion RESULT =null;
		int uleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int uright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Instruccion u = (Instruccion)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT = u; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // stmt ::= db_def 
            {
              Instruccion RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // stmt ::= table_def 
            {
              Instruccion RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // stmt ::= read_stmt 
            {
              Instruccion RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // stmt ::= export_stmt 
            {
              Instruccion RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // stmt ::= add_stmt 
            {
              Instruccion RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // stmt ::= update_stmt 
            {
              Instruccion RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // stmt ::= clear_stmt 
            {
              Instruccion RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // stmt ::= error PUNTO_COMA 
            {
              Instruccion RESULT =null;
		 RESULT = null; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // stmt ::= error LLAVE_CIERRA 
            {
              Instruccion RESULT =null;
		 RESULT = null; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // db_def ::= DATABASE ID LLAVE_ABRE store_opt LLAVE_CIERRA 
            {
              Instruccion RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("db_def",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // db_def ::= DATABASE ID LLAVE_ABRE error LLAVE_CIERRA 
            {
              Instruccion RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("db_def",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // store_opt ::= STORE AT CADENA PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("store_opt",11, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // store_opt ::= 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("store_opt",11, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // use_def ::= USE ID PUNTO_COMA 
            {
              Instruccion RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		
         // ¡AQUÍ ESTÁ LA MAGIA! Instanciamos nuestro nodo del AST
         RESULT = new UseDB(id);
      
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("use_def",4, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // use_def ::= USE error PUNTO_COMA 
            {
              Instruccion RESULT =null;
		
         // Si hubo error, devolvemos null para no meter basura al AST
         RESULT = null;
      
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("use_def",4, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // table_def ::= TABLE ID LLAVE_ABRE col_list LLAVE_CIERRA 
            {
              Instruccion RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("table_def",5, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // table_def ::= TABLE ID LLAVE_ABRE error LLAVE_CIERRA 
            {
              Instruccion RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("table_def",5, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // col_list ::= col_list col_decl 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("col_list",12, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // col_list ::= col_decl 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("col_list",12, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // col_decl ::= ID DOS_PUNTOS type_def PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("col_decl",13, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // type_def ::= T_INT 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("type_def",14, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // type_def ::= T_STRING 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("type_def",14, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // type_def ::= T_FLOAT 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("type_def",14, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // type_def ::= T_BOOL 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("type_def",14, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // type_def ::= T_ARRAY 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("type_def",14, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // type_def ::= T_OBJECT 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("type_def",14, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // read_stmt ::= READ ID LLAVE_ABRE field_decl filter_decl LLAVE_CIERRA PUNTO_COMA 
            {
              Instruccion RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("read_stmt",6, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-6)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // read_stmt ::= READ ID LLAVE_ABRE field_decl LLAVE_CIERRA PUNTO_COMA 
            {
              Instruccion RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("read_stmt",6, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // read_stmt ::= READ ID LLAVE_ABRE field_decl filter_decl LLAVE_CIERRA 
            {
              Instruccion RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 parser.reportar_error_manual("Falta ';' al final de la instrucción 'read'", cleft, cright); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("read_stmt",6, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // read_stmt ::= READ ID LLAVE_ABRE field_decl LLAVE_CIERRA 
            {
              Instruccion RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 parser.reportar_error_manual("Falta ';' al final de la instrucción 'read'", cleft, cright); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("read_stmt",6, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // read_stmt ::= READ ID LLAVE_ABRE error LLAVE_CIERRA PUNTO_COMA 
            {
              Instruccion RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("read_stmt",6, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // read_stmt ::= READ ID LLAVE_ABRE error LLAVE_CIERRA 
            {
              Instruccion RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 parser.reportar_error_manual("Falta ';' al final de la instrucción 'read'", cleft, cright); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("read_stmt",6, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // field_decl ::= FIELDS DOS_PUNTOS id_list PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("field_decl",15, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // field_decl ::= FIELDS DOS_PUNTOS ASTERISCO PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("field_decl",15, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // id_list ::= id_list COMA ID 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("id_list",17, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // id_list ::= ID 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("id_list",17, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // filter_decl ::= FILTER DOS_PUNTOS expr PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("filter_decl",16, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // export_stmt ::= EXPORT CADENA PUNTO_COMA 
            {
              Instruccion RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("export_stmt",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // export_stmt ::= EXPORT error PUNTO_COMA 
            {
              Instruccion RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("export_stmt",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // add_stmt ::= ADD ID LLAVE_ABRE pair_list LLAVE_CIERRA PUNTO_COMA 
            {
              Instruccion RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("add_stmt",8, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // add_stmt ::= ADD ID LLAVE_ABRE pair_list LLAVE_CIERRA 
            {
              Instruccion RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 parser.reportar_error_manual("Falta ';' al final de la instrucción 'add'", cleft, cright); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("add_stmt",8, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // add_stmt ::= ADD ID LLAVE_ABRE error LLAVE_CIERRA PUNTO_COMA 
            {
              Instruccion RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("add_stmt",8, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // add_stmt ::= ADD ID LLAVE_ABRE error LLAVE_CIERRA 
            {
              Instruccion RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 parser.reportar_error_manual("Falta ';' al final de la instrucción 'add'", cleft, cright); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("add_stmt",8, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // pair_list ::= pair_list COMA pair_assign 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("pair_list",19, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // pair_list ::= pair_assign 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("pair_list",19, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // pair_assign ::= ID DOS_PUNTOS value 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("pair_assign",20, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // update_stmt ::= UPDATE ID LLAVE_ABRE SET DOS_PUNTOS assign_list PUNTO_COMA filter_decl LLAVE_CIERRA PUNTO_COMA 
            {
              Instruccion RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("update_stmt",9, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-9)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // update_stmt ::= UPDATE ID LLAVE_ABRE SET DOS_PUNTOS assign_list PUNTO_COMA LLAVE_CIERRA PUNTO_COMA 
            {
              Instruccion RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("update_stmt",9, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-8)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // update_stmt ::= UPDATE ID LLAVE_ABRE SET DOS_PUNTOS assign_list PUNTO_COMA filter_decl LLAVE_CIERRA 
            {
              Instruccion RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 parser.reportar_error_manual("Falta ';' al final de la instrucción 'update'", cleft, cright); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("update_stmt",9, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-8)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // update_stmt ::= UPDATE ID LLAVE_ABRE SET DOS_PUNTOS assign_list PUNTO_COMA LLAVE_CIERRA 
            {
              Instruccion RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 parser.reportar_error_manual("Falta ';' al final de la instrucción 'update'", cleft, cright); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("update_stmt",9, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-7)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // update_stmt ::= UPDATE ID LLAVE_ABRE error LLAVE_CIERRA PUNTO_COMA 
            {
              Instruccion RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("update_stmt",9, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // update_stmt ::= UPDATE ID LLAVE_ABRE error LLAVE_CIERRA 
            {
              Instruccion RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 parser.reportar_error_manual("Falta ';' al final de la instrucción 'update'", cleft, cright); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("update_stmt",9, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // assign_list ::= assign_list COMA assign_elem 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("assign_list",21, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // assign_list ::= assign_elem 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("assign_list",21, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // assign_elem ::= ID IGUAL value 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("assign_elem",22, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // clear_stmt ::= CLEAR ID PUNTO_COMA 
            {
              Instruccion RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("clear_stmt",10, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // clear_stmt ::= CLEAR error PUNTO_COMA 
            {
              Instruccion RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("clear_stmt",10, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // value ::= CADENA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("value",23, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // value ::= ENTERO 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("value",23, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // value ::= DECIMAL 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("value",23, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // value ::= TRUE 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("value",23, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // value ::= FALSE 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("value",23, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // value ::= NULL 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("value",23, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // value ::= array_def 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("value",23, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // array_def ::= COR_ABRE val_list COR_CIERRA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("array_def",24, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // array_def ::= COR_ABRE COR_CIERRA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("array_def",24, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // val_list ::= val_list COMA value 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("val_list",25, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // val_list ::= value 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("val_list",25, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // expr ::= expr OR expr 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expr",18, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // expr ::= expr AND expr 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expr",18, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // expr ::= NOT expr 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expr",18, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // expr ::= PAR_ABRE expr PAR_CIERRA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expr",18, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // expr ::= ID IGUAL_IGUAL value 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expr",18, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // expr ::= ID DIFERENTE value 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expr",18, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // expr ::= ID MAYOR value 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expr",18, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // expr ::= ID MENOR value 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expr",18, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // expr ::= ID MAYOR_IGUAL value 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expr",18, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // expr ::= ID MENOR_IGUAL value 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expr",18, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Sintactico$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Sintactico$do_action(
    int                        CUP$Sintactico$act_num,
    java_cup.runtime.lr_parser CUP$Sintactico$parser,
    java.util.Stack            CUP$Sintactico$stack,
    int                        CUP$Sintactico$top)
    throws java.lang.Exception
    {
              return CUP$Sintactico$do_action_part00000000(
                               CUP$Sintactico$act_num,
                               CUP$Sintactico$parser,
                               CUP$Sintactico$stack,
                               CUP$Sintactico$top);
    }
}

}
